# debug mode
debug: false
# getting metric details
details: true
# hostname specified
hostname: ""
# agent collect interval
interval: 10
# push batch-size metrics per-operation
batchsize: 100
# enable functions
enabled:
  collect: true
  witch: true
  log_rotate: true

# http client settings (timeout in seconds)
http:
  conn_timeout: 10
  response_timeout: 10

# RabbitMQ settings
rabbitmq:
  host: 127.0.0.1
  port: 15672
  user: admin